{{- if .Values.synapse.server.adminUser.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "matrix-synapse.fullname" . }}-admin-job-manager
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-job-manager
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "delete"]
    resourceNames:
      - {{ include "matrix-synapse.fullname" . }}-create-admin
  # Allow listing without resourceName to check if job exists
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "matrix-synapse.fullname" . }}-admin-job-manager
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-job-manager
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "matrix-synapse.fullname" . }}-admin-job-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "matrix-synapse.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
