{{- if .Values.element.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-synapse.fullname" . }}-element-config
  labels:
    {{- include "matrix-synapse.element.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "default_server_config": {
        "m.homeserver": {
          "base_url": "{{ .Values.element.config.defaultServerUrl }}",
          "server_name": "{{ .Values.element.config.defaultServerName }}"
        },
        "m.identity_server": {
          "base_url": "https://vector.im"
        }
      },
      "brand": "Element",
      "integrations_ui_url": "{{ .Values.element.config.integrations.uiUrl }}",
      "integrations_rest_url": "{{ .Values.element.config.integrations.restUrl }}",
      "integrations_widgets_urls": {{ .Values.element.config.integrations.widgetsUrls | toJson }},
      "integrations_jitsi_widget_url": "https://scalar.vector.im/api/widgets/jitsi.html",
      "bug_report_endpoint_url": "https://element.io/bugreports/submit",
      "default_country_code": "FR",
      "show_labs_settings": {{ .Values.element.config.features.showLabsSettings }},
      "default_federate": true,
      "default_theme": "dark",
      "room_directory": {
        "servers": {{ .Values.element.config.roomDirectory.servers | toJson }}
      },
      {{- if .Values.element.config.welcomeUserId }}
      "welcomeUserId": "{{ .Values.element.config.welcomeUserId }}",
      {{- end }}
      "enable_presence_by_hs_url": {
        "{{ .Values.element.config.defaultServerUrl }}": true
      },
      "setting_defaults": {
        "breadcrumbs": true,
        "UIFeature.urlPreviews": true,
        "urlPreviewsEnabled": true,
        "theme": "dark"
      },
      "features": {
        "feature_url_previews": "enable"
      },
      "jitsi": {
        "preferred_domain": "meet.jit.si"
      }{{- if and .Values.element.config.branding (or .Values.element.config.branding.authHeaderLogoUrl .Values.element.config.branding.welcomeBackgroundUrl) }},
      "branding": {
        {{- if .Values.element.config.branding.authHeaderLogoUrl }}
        "auth_header_logo_url": "{{ .Values.element.config.branding.authHeaderLogoUrl }}"{{- if .Values.element.config.branding.welcomeBackgroundUrl }},{{- end }}
        {{- end }}
        {{- if .Values.element.config.branding.welcomeBackgroundUrl }}
        "welcome_background_url": "{{ .Values.element.config.branding.welcomeBackgroundUrl }}"
        {{- end }}
      }{{- end }},
      "custom_themes": [
        {
          "name": "Dark",
          "is_dark": true,
          "colors": {
            "accent-color": "#0dbd8b",
            "primary-color": "#0dbd8b",
            "warning-color": "#ff6b6b",
            "alert": "#ff6b6b",
            "sidebar-color": "#15191e",
            "roomlist-background-color": "#15191e",
            "roomlist-text-color": "#ffffff",
            "roomlist-text-secondary-color": "#adbac7",
            "roomlist-highlights-color": "#0dbd8b",
            "roomlist-separator-color": "#444c56",
            "timeline-background-color": "#21262c",
            "timeline-text-color": "#ffffff",
            "timeline-text-secondary-color": "#adbac7",
            "timeline-highlights-color": "#0dbd8b",
            "reaction-row-button-selected-bg-color": "#2d333b",
            "menu-bg-color": "#2d333b",
            "menu-selected-color": "#373e47",
            "focus-bg-color": "#2d333b",
            "room-highlight-color": "#0dbd8b",
            "other-user-pill-bg-color": "#2d333b",
            "username-colors": ["#0dbd8b", "#539bf5", "#9d70f5", "#f778ba", "#ff6b6b", "#ff8b3d", "#ffc53d", "#7ee787"],
            "avatar-background-colors": ["#0dbd8b", "#539bf5", "#9d70f5", "#f778ba", "#ff6b6b", "#ff8b3d", "#ffc53d", "#7ee787"]
          }
        }
      ]
    }
{{- end }}
