{{- if .Values.element.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matrix-synapse.fullname" . }}-element
  labels:
    {{- include "matrix-synapse.element.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.element.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "matrix-synapse.element.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/element-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "matrix-synapse.element.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.element.podSecurityContext | nindent 8 }}
      containers:
        - name: element-web
          securityContext:
            {{- toYaml .Values.element.securityContext | nindent 12 }}
          image: "{{ .Values.element.image.repository }}:{{ .Values.element.image.tag }}"
          imagePullPolicy: {{ .Values.element.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.element.resources | nindent 12 }}
          volumeMounts:
            - name: element-config
              mountPath: /app/config.json
              subPath: config.json
              readOnly: true
            - name: dark-theme-css
              mountPath: /app/bundles/dark-theme.css
              subPath: dark-theme.css
              readOnly: true
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: element-config
          configMap:
            name: {{ include "matrix-synapse.fullname" . }}-element-config
        - name: dark-theme-css
          configMap:
            name: {{ include "matrix-synapse.fullname" . }}-element-dark-css
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
        - name: nginx-conf
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
