{{- if .Values.mas.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix-synapse.fullname" . }}-mas
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: mas
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "matrix-synapse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mas
{{- end }}
