{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "matrix-synapse.fullname" . }}-postgresql
  labels:
    {{- include "matrix-synapse.postgresql.labels" . | nindent 4 }}
{{- end }}
