{{- if and (eq (.Values.postgresql.mode | default "cnpg") "standalone") .Values.postgresql.standalone.postgresPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-synapse.fullname" . }}-postgresql
  labels:
    {{- include "matrix-synapse.postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.standalone.postgresPassword | b64enc | quote }}
{{- end }}
