{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-synapse.fullname" . }}-postgresql-config
  labels:
    {{- include "matrix-synapse.postgresql.labels" . | nindent 4 }}
data:
  postgresql.conf: |
    # PostgreSQL Configuration for Matrix Synapse
    # Optimized for Synapse workload

    # Connection Settings
    max_connections = {{ .Values.postgresql.config.maxConnections }}
    superuser_reserved_connections = 3

    # Memory Settings
    shared_buffers = {{ .Values.postgresql.config.sharedBuffers }}
    effective_cache_size = {{ .Values.postgresql.config.effectiveCacheSize }}
    maintenance_work_mem = {{ .Values.postgresql.config.maintenanceWorkMem }}
    work_mem = {{ .Values.postgresql.config.workMem }}

    # WAL Settings (minimal for single-instance)
    wal_level = {{ .Values.postgresql.config.walLevel }}
    max_wal_senders = {{ .Values.postgresql.config.maxWalSenders }}

    # Query Tuning
    random_page_cost = 1.1
    effective_io_concurrency = 200

    # Logging Configuration
    # Slow query logging
    log_min_duration_statement = {{ .Values.postgresql.config.logMinDurationStatement }}

    # Connection logging
    {{- if .Values.postgresql.config.logConnections }}
    log_connections = on
    {{- else }}
    log_connections = off
    {{- end }}
    {{- if .Values.postgresql.config.logDisconnections }}
    log_disconnections = on
    {{- else }}
    log_disconnections = off
    {{- end }}

    # Statement logging
    {{- if .Values.postgresql.config.logStatement }}
    log_statement = '{{ .Values.postgresql.config.logStatement }}'
    {{- end }}

    # Log level and verbosity
    {{- if .Values.postgresql.config.logStatementLevel }}
    log_min_messages = {{ .Values.postgresql.config.logStatementLevel }}
    {{- end }}
    {{- if .Values.postgresql.config.logErrorVerbosity }}
    log_error_verbosity = {{ .Values.postgresql.config.logErrorVerbosity }}
    {{- end }}

    # Log line format
    {{- if .Values.postgresql.config.logLinePrefix }}
    log_line_prefix = '{{ .Values.postgresql.config.logLinePrefix }}'
    {{- end }}

    # Additional logging options
    {{- if .Values.postgresql.config.logLockWaits }}
    log_lock_waits = on
    {{- else }}
    log_lock_waits = off
    {{- end }}
    {{- if .Values.postgresql.config.logTempFiles }}
    log_temp_files = {{ .Values.postgresql.config.logTempFiles }}
    {{- end }}
    {{- if .Values.postgresql.config.logAutovacuumMinDuration }}
    log_autovacuum_min_duration = {{ .Values.postgresql.config.logAutovacuumMinDuration }}
    {{- end }}

    # Locale and Encoding
    lc_messages = 'C'
    lc_monetary = 'C'
    lc_numeric = 'C'
    lc_time = 'C'

    # Other Settings
    default_text_search_config = 'pg_catalog.english'
{{- end }}
