{{- if .Values.rtc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix-synapse.fullname" . }}-element-call
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: element-call
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "matrix-synapse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: element-call
{{- end }}
