{{- if .Values.synapseAdmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix-synapse.fullname" . }}-synapse-admin
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: synapse-admin
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "matrix-synapse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: synapse-admin
{{- end }}
