name: Helm Chart CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Helm lint
        run: |
          helm lint .

      - name: Helm template test (dry-run)
        run: |
          helm template matrix-synapse . \
            --set postgresql.auth.password=test-password \
            --set synapse.server.registrationSharedSecret=test-secret \
            --debug

  release:
    needs: lint-test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Package Helm chart
        run: |
          helm package .

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tgz
