name: Helm Chart CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Helm lint
        run: |
          helm lint .

      - name: Helm template test (dry-run)
        run: |
          helm template matrix-synapse . \
            --set postgresql.auth.password=test-password \
            --set synapse.server.registrationSharedSecret=test-secret \
            --debug

  publish:
    needs: lint-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Package Helm chart
        run: |
          helm package .

      - name: Clone gh-pages or create new
        run: |
          if git fetch origin gh-pages 2>/dev/null; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git rm -rf . || true
            git clean -fxd
          fi

      - name: Copy package and update index
        run: |
          git checkout main -- *.tgz 2>/dev/null || true
          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
          git add -f *.tgz index.yaml

      - name: Commit and push
        run: |
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Helm repository - $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin gh-pages || git push --set-upstream origin gh-pages
          fi

  release:
    needs: lint-test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Package Helm chart
        run: |
          helm package .

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tgz
